image: texlive/texlive

stages:
  - build

building-latex-master:
  stage: build
  script:
    - cd paper
    - latexmk -bibtex -pdf main.tex
  artifacts:
    paths:
      - "paper/main.tex"
    expire_in: 2 years
  only:
    - master

building-latex-other-branch:
  stage: build
  script:
    - cd paper
    - latexmk -bibtex -pdf main.tex
  artifacts:
    paths:
      - "paper/main.pdf"
    expire_in: 2 weeks
  except:
    - master

building-markdown-master:
  image: ntwrkguru/pandoc-gitlab-ci
  stage: build
  script:
    - pandoc -s ./paper/main.tex  -o ./temp.md
  artifacts:
    paths:
      - "temp.md"
    expire_in: 1 hour
  only:
    - master
